server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wealthbuddy
    username: wealthbuddy
    password: wealthbuddy123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.wealthbuddy: DEBUG